### ISSUE TITLE
Rabbitmq Queue not being auto-deleted

### ISSUE THREAD

**Issue by arvindn05** [opensecuritycontroller/osc-core#203]
Sometime the rabbitmq queue osc_queue is not being auto deleted like it supposed to. Seems to be an RabbitMQ issue. Best practise is to add ttl for every queue created so it gets deleted automatically.
http://www.rabbitmq.com/ttl.html#queue-ttl

```
Map<String, Object> args = new HashMap<String, Object>();
args.put("x-expires", 1800000);
channel.queueDeclare("myqueue", false, false, false, args);
```

**Comment by larkinscarvalho** [comment]
@arvindn05 Not Reproduced.

### Observations:
- Restarting OSC Server terminates the queue
- Deleting Virtualization Connector terminates the queue

### Environment
- OSC Version/Build: Build:118-g0a08063
- Cloud Provider Versions: Mitaka and Ocata

**Comment by arvindn05** [comment]
@larkinscarvalho what scenarios did you try to reproduce the issue?

**Comment by larkinscarvalho** [comment]
@arvindn05 
RabbitMQ delete scenarios: 
- Restarting OSC Server terminates the queue
- Deleting Virtualization Connector terminates the queue

Unhandled scenarios:
- Deleting NIC of OSC : deletes queue

**Comment by arvindn05** [comment]
not sure what it means by unhandled scenarios...but if we cannot repro the issues....lets just add a reasonable time out for the queue and close the issue. 

Folks can reopen if they find the issue happens again

**Comment by arvindn05** [comment]
@alin2k please update this bug

**Comment by ychoma** [comment]
Albert verified it
