### ISSUE TITLE
Potential backwards compatibility problem with some APIs

### ISSUE THREAD

**Issue by emanoelxavier** [opensecuritycontroller/osc-core#258]
This issue is related to the PR #256 . That PR turns additional entity enums used in the DTOS into strings. We must discuss further whether this can cause a real compatibility problem and, if so, maybe replicate those enums in the API service. 
@derekwb  I will leave this issue assigned to myself for now to discuss with @arvindn05 upon his return. We will assign to you in case this is something we must fix.

**Comment by arvindn05** [comment]
AcknowledgementStatus, object type need to be moved to common project
