### ISSUE TITLE
API requests failing with parse exception

### ISSUE THREAD

**Issue by arvindn05** [opensecuritycontroller/osc-core#321]
For the adding VC
==============================================================================
DEBUG - createOstackVC
-- Sending POST Request for Action: create Virtualization Connector:
-- IP Addr: "10.3.205.104:8090"
-- Headers: "JSON"
-- URL: "/api/server/v1/virtualizationConnectors"
 
-- Body:
 
        {
            "name": "104-VC",
            "type": "OPENSTACK",
            "providerIP": "10.3.205.92",
            "providerUser": "admin",
            "providerPassword": "admin123",
            "softwareVersion": "Icehouse",
            "controllerType": {
                "value": "NONE"
            },
            "adminTenantName": "admin",
            "skipRemoteValidation": true,
            "forceAddSSLCertificates": true,
           
            "providerAttributes": {
                "ishttps": "false",
                "rabbitMQPort": "5672",
                "rabbitUser": "guest",
                "rabbitMQPassword": "guest"
            }
       
        }

 

DEBUG - Enter get_exception_info  Exception: "_isc_connection:  Status 400 for create Virtualization Connector: Bad Request b'{"errorCode":4000,"errorMessages":["Parse exception. Invalid request."]}'"
 
 
For adding MC
==============================================================================
DEBUG - _isc_connection -- Sending POST Request for Action: create Manager Connector/createOrUpdateManagerConnector:
-- IP Addr: "10.3.205.104:8090"
-- Method: "POST"
-- Headers: "{'Authorization': 'Basic YWRtaW46YWRtaW4xMjM=', 'Content-Type': 'application/json', 'Accept': 'application/json'}"
-- URL: "/api/server/v1/applianceManagerConnectors"
 
-- Body:
 
        {
            "name": "104-MC",
            "managerType": {
                 "value": "NSM"
            },
            "ipAddress": "10.3.205.105",
            "username": "admin",
            "password": "admin123",
            "skipRemoteValidation": true,
            "forceAddSSLCertificates": true,
            "isPolicyMappingSupported": false
        }

DEBUG - Enter get_exception_info  Exception: "_isc_connection:  Status 400 for create Manager Connector/createOrUpdateManagerConnector: Bad Request b'{"errorCode":4000,"errorMessages":["Parse exception. Invalid request."]}'"

Tested the same requests using 0.6 and they seem to work fine. used version 0.6 (Build:35-g00caf91)

You can test out the above requests by going into osc 

> https://OSC-IP:8090/api-doc/ and using swagger doc to submit and test the requests with the payload.

**Comment by emanoelxavier** [comment]
I am closing this bug as the create requests for VC and MC are currently working with the payloads mentioned by arvind above. This was addressed as part of the creation of the osc-common project.

**Comment by emanoelxavier** [comment]
@ychoma I have looked at this issue and it is no longer happening. It was indeed fixed by a previous code change. I am assigning this defect to you so you can confirm that. Once you confirm please mark the Status [x] Validated
