### ISSUE TITLE
Inspection ports are deleted in the SDN controller only if it supports port group

### ISSUE THREAD

**Issue by emanoelxavier** [opensecuritycontroller/osc-core#347]
Currently the task DeleteInspectionPortTask task is only being executed if the SDN controller supports port group. This task should be included for ALL sdn controllers.

**Comment by arvindn05** [comment]
Should be fixed as part of the SFC feature.

**Comment by arvindn05** [comment]
@dmitryintel DeleteSvaServerAndDAIMetaTask has this check

**Comment by arvindn05** [comment]
@mrajora-1 please test after dmitrys changes and close

**Comment by mrajora-1** [comment]
Tested and verified earlier right after the fix but do not remember the build. Verified with NSC and SFC.
