### ISSUE TITLE
Travis check fails on OSC 0.6

### ISSUE THREAD

**Issue by larkinscarvalho** [opensecuritycontroller/osc-core#359]
We are able to generate the parametrized/local build. However, Travis checks fails for the same pull request.

[Travis build](https://travis-ci.com/opensecuritycontroller/osc-core/builds/49323602)

**Comment by arvindn05** [comment]
@larkinscarvalho the link is no longer accessible and there are no details....please let us know if this is still an issue or can be closed

**Comment by larkinscarvalho** [comment]
Issue has been fixed.
