### ISSUE TITLE
When deleting and immediately creating MC (through automation) sync MC job fails

### ISSUE THREAD

**Issue by ychoma** [opensecuritycontroller/osc-core#376]
### Expected Behavior
New MC will be added - and sync will succeed

### Actual Behavior
New MC will be added - but sync is failing

### Steps to Reproduce
Have an MC run through automation delete and create a new one

### Additional Information
All tasks of sync job succeed, except the one that sync the domains.

### Status
- [x] Reproduced
- [x] In Progress
- [x] Validated

[SyncingDomainsError.zip](https://github.com/opensecuritycontroller/osc-core/files/1149191/SyncingDomainsError.zip)

![syncing domains error](https://user-images.githubusercontent.com/26880884/28222707-86fa7760-687d-11e7-9601-851d6224c34c.PNG)

**Comment by ychoma** [comment]
Logs are in SyncingDomainsError.zip file.

**Comment by arvindn05** [comment]
@ychoma is this consistently reproducible? If not can you provide details on the steps?

**Comment by ychoma** [comment]
Verified by automation with build Version: 1.0.0-SNAPSHOT (Build:37-g6ed4efb, 2017-07-30T22:51:00Z)
