### ISSUE TITLE
SDN Controller Plugin reload issue

### ISSUE THREAD

**Issue by ashutosh-mishra** [opensecuritycontroller/osc-core#383]
Observed 2 issues w.r.t plugin load/unload
1) As part of plugin load, OSC installs plugin as bundle, which invokes start() method of bundle context. And as part of unload, stop() method of bundle gets invoked.
After loading plugin, if user clicks on any tab, then stop() method of bundle  gets invoked, but plugin is not removed from context and still loaded in OSC. This'll remove any initialization done as part of start(), which is not an intended behavior. Ideally stop() methos should get called only if plugin gets unloaded.
This is a consistent behavior

2) Sometimes plugin doesn't get loaded properly i.e. some of the classes/libraries of plugin doesn't gets initialized/exist. UI shows that plugin gets loaded successfully, but at time of bind plugin throws exception when it tries to access those class/libraries. Looks like at time of plugin unload cleanup not happened properly, which is affecting next plugin load.
This is an inconsistent behavior, observed issue few times only.
To resolve this issue, user need to restart osc-server after every plugin unload, to cleanup context properly.

**Comment by emanoelxavier** [comment]
Hi @ashutosh-mishra Thanks for tracking this issue. Can you please update this and the other issue you opened with the issue tracking template? The purpose of the template is to ensure consistency, clarity, help track the issue status and support the triage process. For details please see https://github.com/opensecuritycontroller/community/blob/master/development/issue_tracking.md

**Comment by arvindn05** [comment]
@dmitryintel any updates? Please evalute and let us know if its a valid issue or it can be closed.

**Comment by dmitryintel** [comment]
Sounds like @ashutosh-mishra is writing his own plugin. 

I would suggest that he write the OSGi `@Component` class to be a factory for the API object which he really wants to use. For example, in the NSFC plugin, the [NeutronSfcSdnControllerApi](https://github.com/opensecuritycontroller/sdn-controller-nsfc-plugin/blob/master/src/main/java/org/osc/controller/nsfc/api/NeutronSfcSdnControllerApi.java) component is a factory for [NeutronSfcSdnRedirectionApi](https://github.com/opensecuritycontroller/sdn-controller-nsfc-plugin/blob/master/src/main/java/org/osc/controller/nsfc/api/NeutronSfcSdnRedirectionApi.java), which is the thing that actually has all the desired functionality. We quickly use the factory to create the service API discard. 

This way, there is no harm in calling `start()` and `stop()` methods on `NeutronSfcSdnControllerApi` all the time. BTW, the `stop()`, does not even exist. 

To give you more detail, I debugged into the code, and when I enter and leave the _Plugin_ tab, `context.getService` and `context.ungetService` get called on the `SdnControllerApi`, and those trace down to `start()` and `stop()` methods. There is no guarantee that the component exists if nobody is actually using it, so the framework destroys the unused service. 

Two alternative approaches to this suggestion are:
- add `immediate=true` attribute into the `@Component` annotation. This way, the component gets instantiated as soon as possible, not lazily, and lives as long as the containing bundle is active. 
- Another hackish solution is to put an `if (alreadyInitialized)` condition into `start()` so the initialization happens only once.

**Comment by sudhirappaji** [comment]
@ashutosh-Mishra, hope the above information is sufficient and solves the problem. Incase if we don't hear anything from you in 2 weeks, we shall close this.

**Comment by sudhirappaji** [comment]
we assume that the above information is sufficient and closing it now.
