### ISSUE TITLE
OSC is unable to sync security group of type subnet when a new VM is created

### ISSUE THREAD

**Issue by ashutosh-mishra** [opensecuritycontroller/osc-core#384]
In case of Security group with type subnet is protected, when new VMs added in the subnet  these are not being protected due to delay in osc-server in sending a trigger to SDN plugin to redirect the traffic for protection.
As a workaround, whenever a new VM is added in the subnet which is protected by a security group of type Subnet, user needs to do trigger manual sync of the security group from OSC UI, to protect new vms.
Observed issue only when security group protects subnet, with network case this is working fine.

Steps to reproduce:
=====
1. Followed [openstack user workflow](https://github.com/opensecuritycontroller/opensecuritycontroller.org/blob/master/tutorials/openstack_workload.md#set-up-osc-to-protect-a-workload) and successfully created Deployment Spec.
2. Created a Security group (SG) with type Subnet
3. Bind this SG with the VNF
4. The subnet is protected successfully i.e. existing vms gets protected properly.
5. Now created a new openstack VM in the above subnet.
6. The issue is that OSC doesn't sync the SG automatically. As a result the newly created vm is not protected.

**Comment by arvindn05** [comment]
@ashutosh-mishra can you provide logs from OSC?

There are cases where this is valid behaviour. see following lines 

https://github.com/opensecuritycontroller/osc-core/blob/HEAD/osc-server/src/main/java/org/osc/core/broker/rest/client/openstack/vmidc/notification/listener/OsPortNotificationListener.java#L136

if ((subnet.isProtectExternal() && deviceOwner.startsWith("compute:"))
                            || (!subnet.isProtectExternal() && deviceOwner.equals(""))) {
                        // we ignore message and do not trigger sync...

**Comment by arvindn05** [comment]
@alin2k please reproduce and test as part of the fix for #462

**Comment by alin2k** [comment]
See it is fixed in #462
