### ISSUE TITLE
api-doc MC GET and POST have wrong name "PolicyMappingSupported", should be "isPolicyMappingSupported"

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#394]
### Description
In https://OSCipaddress:8090/api-doc, Operations for Manager Connectors section there are three GETs, POST, PUT all have field name "PolicyMappingSupported", POST did get "bad request, un-recognize field", so all 5 places need to name it as "**is**PolicyMappingSupported". POST may even take this field out (not needed)
### Expected Behavior
User can use api-doc to test Rest API functions OSC provides
### Actual Behavior
POST/PUT failed. GET Model Schema display can confuse user with wrong name.

### Steps to Reproduce
1)https://OSCipaddress:8090/api-doc, Operations for Manager Connectors section
2)GET Model Schema display in the yellow box
3)POST/PUT click write box and real fields in yellow box has wrong name and causes request fauiled
### Additional Information
screenshot attached.
### Environment
- OSC Version/Build: v1B30
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [x] Reproduced
- [x] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

<img width="413" alt="apidocgetmcs" src="https://user-images.githubusercontent.com/11319375/28649308-d4987b16-7228-11e7-91a6-487da586bd24.PNG">
<img width="386" alt="apidocpostmcs" src="https://user-images.githubusercontent.com/11319375/28649309-d9b4109c-7228-11e7-9054-304ef414af5c.PNG">

**Comment by alin2k** [comment]
v0.8 Build#118: Looks like fixed doc in MC GET but not in MC POST? (Issue is still OPEN):
...
"policyMappingSupported": false

**Comment by larkinscarvalho** [comment]
@alin2k How did you verify the MC GET? 
Issue is not yet fixed. Also, the dev task is in progress on rally.

**Comment by alin2k** [comment]
- [x] Validated     =>    Verified fix in Version/Build: v0.8 Build#123
