### ISSUE TITLE
How to change UI http port ?

### ISSUE THREAD

**Issue by vkochan** [opensecuritycontroller/osc-core#401]
### Description
How to change UI http port ?

### Expected Behavior
UI is opened via 8080 port

### Actual Behavior
UI is opened via 80 port

### Steps to Reproduce
In vmidc.sh:
JAVA_OPTS="$JAVA_OPTS  -Dorg.osgi.service.http.port=8080 -Djetty.port=8080 -Djetty.http.port=8080"

### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
All of OSC HTTP/servlet config is under the following folder.

https://github.com/opensecuritycontroller/osc-core/tree/master/osc-export/config

you can use the org.apache.felix.http* config files to configure the API/UI ports

**Comment by arvindn05** [comment]
@vkochan Please close this issue if the comment addresses the problem/.

**Comment by vkochan** [comment]
Sure I will do it

**Comment by vkochan** [comment]
Hm, after I changed this:

# osc-core-/osc-server-bom/root/opt/vmid/bin/config/org.apache.felix.http-redirect.cfg
org.osgi.service.http.port=10080

#  osc-core/osc-server-bom/root/opt/vmid/bin/config/org.apache.felix.http-ui.cfg
org.osgi.service.http.port.secure=10443

I go to the 127.0.0.1:10080, and redirected to 10443 with the following error:

Failed to load the widgetset: ./VAADIN/widgetsets/org.osc.core.broker.view.AppWidgetSet/org.osc.core.broker.view.AppWidgetSet.nocache.js?1501998162506

with a blank page.

**Comment by arvindn05** [comment]
generally a refresh should solve the problem. If not i would recommend a full build after the config change and see if the problem still exists.

**Comment by vkochan** [comment]
Yeap, rebuild solved the issue, Thanks !!!
