### ISSUE TITLE
FMR: Restore a backed up DB to an OSC  Add a red 'Expired Session bar' at the top which can be used to login - like we see after upgrade of OSC

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#413]
### Description
FMR: Restore a backed up DB to an OSC  Add a red 'Expired Session bar' at the top which can be used to login - like we see after upgrade of OSC

### Additional Information
DE3267 in Rally

### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![20-restore-login-back-in-few-mins](https://user-images.githubusercontent.com/28600997/29147437-e4b97e84-7d1b-11e7-9837-b1fe4b8b9e84.JPG)

![21-red-session-expired-bar](https://user-images.githubusercontent.com/28600997/29147450-f0c7d20c-7d1b-11e7-817d-2a48318a3e8b.JPG)

**Comment by arvindn05** [comment]
@mrajora-1 can you fill in the fields and add more detail?

**Comment by larkinscarvalho** [comment]
Please attach the logs.

**Comment by arvindn05** [comment]
We dont see the issue. In both DB restore and server upgrade we always restart the server and when the server restarts you should see the bar.

@mrajora-1 please recheck and let us know

**Comment by mrajora-1** [comment]
Tested with Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
Yes I see the red bar now after db restore. So I will close this bug. However, I see 2 more issues with restore and will be opening new bugs for those. 

![restore-successful](https://user-images.githubusercontent.com/28600997/31630383-4b0b32de-b26b-11e7-89a4-0e5cd2871f65.JPG)

![red-bar-on-top-after-db-restore](https://user-images.githubusercontent.com/28600997/31630390-4fd01a3c-b26b-11e7-896d-a2934b2dbbbf.JPG)
