### ISSUE TITLE
Selection Type for Security Group by Type displays Vm - it should be displayed as VM (as VM is an abbreviation for Virtual Machines)

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#418]
### Steps to Reproduce
On OSC/Setup/Virtualization Connector/, add  a Security Group. 
Selection type column displays Vm. 
It should be displayed as VM as VM is an abbreviation for Virtual Machines. 
Earlier it was 'VM'. Dont know how it got changed to Vm. 
We should change it back to 'VM'

Screen shot should suffice for this bug. 

### Additional Information
DE4038 in Rally 

### Environment
- OSC Version/Build: 0.6 (Build:29-g0adc599, 2017-05-09T01:59:44Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![sg-displaying-vm-instead-of-vm](https://user-images.githubusercontent.com/28600997/29148374-b38b866c-7d21-11e7-81e1-206f74a9e2f9.JPG)

**Comment by pravinrajr9** [comment]
This issue can no more reproducible in latest OSC version
Tested with
[sg create](https://user-images.githubusercontent.com/30862177/34215389-3778c144-e5cb-11e7-872b-2bb4258fa789.png)
 Build: Build:171-g9da3d6a, 2017-12-18T06:25:16Z
