### ISSUE TITLE
SG Bind - SG Sync for 'Network' not working appropriately (passes when it should have failed) after deleting Inspection interface from the router on Openstack

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#420]
### Description
SG Bind - SG Sync for 'Network' not working appropriately (passes when it should have failed) after deleting Inspection interface from the router on Openstack.

### Expected Behavior
The Sync Job should have FAILED after inspection interface is detached from the router ( (No appliance instance found in a network assigned to the router/domain (id of router) )

WORKAROUND - Unbind the SG, Bind again. Now the Job will FAIL. 

NOTE - Once the job FAILS and the inspection interface is added to the router, then the Sync PASSES as expected. 

### Actual Behavior
The SG Sync returns a PASSED job. The Job should have FAILED as inspection interface is detached from the router.

### Steps to Reproduce
The bug is a copy of bug [DE3662 in Rally)] https://github.com/opensecuritycontroller/osc-core/issues/416 with the only difference that Selection type is 'Network' instead of VM. 

DESCRIPTION OF ORIGINAL BUG DE3662

Use this just as steps to repro the bug

**********************************************

Testing SG Binding across tenants and Domains

Create a DA - da-1, Create a DS - ds-1 using tenant - admin, selection Host - compute1.localdomain, management network - mgmt-net, inspection network - insp-net and floating IP Pool - ext-net.  

Now create a SG - sg-100, using tenant - admin, By Type VM, and add Victim as its member.  Bind the SG to da-1. The Bind is PASSED.  

Now from the network topology, delete the inspection interface attached to the router. Then do an SG Sync. The SG Sync returns a PASSED job. The Job should have FAILED as inspection interface is detached from the router.

### Additional Information
DE4134 in Rally

### Environment
- OSC Version/Build: 0.6.0-Build:4-gc4547e9, 2017-05-26T07:48:25Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
duplicate of #416
