### ISSUE TITLE
We should have an option to populate the Security Group with a list of VMs when Selection Type is 'All Servers belonging to Project'

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#425]
### Description
VC->SG Add: Will be nice to have a list of all VMs displayed as an option, when the user so desires.
### Expected Behavior
Will be nice to have a list of all VMs displayed as an option, when the user so desires.
### Actual Behavior
blank
### Additional Information
Merged DE2959
![display-list-of-vms-when-sg-is-all-servers-belonging-to-tenant](https://user-images.githubusercontent.com/11319375/29183418-79e28bf4-7db7-11e7-981a-adcf4d17e7c2.JPG)

### Environment
- OSC Version/Build: v2.5B4025
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
Currently working on a feature to expose the IP/MAC and membership information in the security group. Should be fixed by this.

**Comment by arvindn05** [comment]
fixed by 3debe7677f3320494bfe7d60bf3711c545e98c01
@mrajora-1 please verify and close

**Comment by mrajora-1** [comment]
With the implementation of feature - Expose IP/MAC via UI, this bug has been addressed. Now we can see all the VMs along with their port IDs, IPs and MACs by clicking on the 'Membership' button on the Security Groups' page. Hence closing the bug.
