### ISSUE TITLE
IllegalArgumentException when creating a Deployment Spec (DS) - Environment NUAGE

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#429]
### Description
Environment - Nuage
Getting an IllegalArgumentException when creating a Security Group.
### Actual Behavior
This should be tackled by the openstack4j changes.
### Additional Information
Merged DE2932
### Environment
- OSC Version/Build: v2.6B4031
[DE2932log.txt](https://github.com/opensecuritycontroller/osc-core/files/1215839/DE2932log.txt)

- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
should be fixed by 936f53fd0a563d77b9ba744fbefd76fec5ae8793.

Please try and reproduce this issue.

**Comment by mrajora-1** [comment]
Was fixed earlier and we were able to do end-to-end testing for Nuage.
