### ISSUE TITLE
Backup/Restore: Ism DA sync during restore fails

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#433]
### Description
Sync the ISM DA again after the server start finish
Still fails with the same error. 
### Steps to Reproduce
Create ISM Manager Connector(ISM-1, ISM / 1.1.1.1 / aaa/aaa)
AutoImport Cirros-TCPD / ISM / 0.3.0.600 2NIC tcpDump capable Appliance software)
Create ISM DA (DA-ISM / ism MC / VC) and create DeploymentSpec for the DA-ISM
Backup the server : Version: 0.6 (Build:18-g20ea013, 2017-04-25T20:02:46Z)
Shutdown the server
Deploy OSC Version: 0.6 (Build:19-gdcd909f, 2017-04-26T00:27:01Z)
Import ISM Plugin
Restore previously saved backup DB
DA and Deployment Spec fail to sync during conformance.
Error in job failed shows: No entity found for query
### Additional Information
Merged DE3968
### Environment
- OSC Version/Build: v0.6B19
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 
https://rally1.rallydev.com/slm/attachment/112608126316/securityBroker.log

**Comment by arvindn05** [comment]
@alin2k remove link to rally.

Also can you check by running a full sync on the DA? From the logs it does not look like a sync on the DA/MC is being run

**Comment by alin2k** [comment]
Latest Build#85 Add DA got Job Failed: There was an error in Transition completion. Could not re-produce this issue.
