### ISSUE TITLE
FOR NSC SDN Controller, the default Chaining Failure Policy should be FAIL_CLOSE (as of now it is FAIL_OPEN)

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#434]
### Description
The default Chaining Failure Policy for DAs should be FAIL_CLOSE instead of FAIL_OPEN, when the SDN Controller used is NSC, as NSC does not support Service Function Chaining.
### Expected Behavior
The default Chaining Failure Policy for DAs should be FAIL_CLOSE, when it is not supported by the SDN Controller (e.g. NSC)
### Actual Behavior
As of now default is FAIL_OPEN.
### Additional Information
Merged DE2960
### Environment
- OSC Version/Build: v2.5B4025
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@alin2k remove link to rally.

Also NSC plugin does not support failure policy so that field needs to be ignored.
#432 addresses the inconsistency.
