### ISSUE TITLE
Newton Openstack - Deleting and Creating a DS using DA with a Cirros image, creates 2 images on openstack. The same image should have been used on openstack

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#436]
### Description
Newton Openstack - Deleting and Creating a DS using DA with a Cirros image, creates 2 images on openstack. The same image should have been used. 

### Expected Behavior
The same image should have been used for multiple DS instances. 

### Actual Behavior
Different images get created on Openstack

### Steps to Reproduce
Create a DA using a Cirros image. 

Create a DS on OSC - Corresponding instance, image, Openstack SG and flavor get created on Openstack

Delete the above DS. Instance on openstack gets deleted but image, openstack SG and flavor do not get deleted

Now Create another DS on OSC using the same DA - Noticed that 2 images were created on Openstack. 

### Additional Information
DE4231 in Rally

NOTE - Observed only on Newton environment not on Mitaka. 
WORKAROUND - Delete DA and then re-create the DA and DS. 

Add the image properties on the new image for accessing Console of Cirros and test redirection. 

openstack image set --property hw_vif_model=virtio --property hw_disk_bus=ide [image-name or id]

### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@mrajora-1 how does this relate to #435 . Seems the bugs are inconsistent since the other one says we fail with an error. possibly dups?

**Comment by mrajora-1** [comment]
Yes looks like a Dup of 435.
