### ISSUE TITLE
pluginProperties: Uploading an invalid plugin (missing properties) should display an appropriate error message

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#438]
### Description
It should also show an error message on the ‘Info’ column indicating that the plugin has a missing property.
If plugin uploaded this invalid sample file, MC conn cannot displayed with pop-up red error: Cannot populate MC table (attached).
### Expected Behavior
This invalid plugin.bar should be rejected in front, e.g If v2.6 uploaded a v2.5 plugin, got brown warning popup (screenshot  attached)
### Steps to Reproduce
1)Delete built in good NsmMgrPlugin
2)Upload attached invalid_nsm plugin (Firefox browser got 30secs NotResponding by this? Chrome is ok)
3)Lower right blue text said "Successfully uploaded xx" (screenshot attached)
4)State becomes "INSTALL_WAIT" forever, will not be "READY"
### Additional Information
DE3546
### Environment
- OSC Version/Build: master Build109
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

### Attached:
https://rally1.rallydev.com/slm/attachment/99710154860/NsmMgrPlugin_invalid_property.bar
https://rally1.rallydev.com/slm/attachment/99710156984/upldInvalidPluginNsmPassS.PNG
https://rally1.rallydev.com/slm/attachment/99710157416/invalidIsm25pluginUploadMsgS.PNG
https://rally1.rallydev.com/slm/attachment/99757209984/upldInvalidPluginNsmFailed%20to%20populateMcTblS.PNG

**Comment by arvindn05** [comment]
@alin2k please remove rally links.

Plugins are expected to be validated by the plugin provider. The information is collected in the logs for why the plugin installation failed. No reason to display the same information to a customer.
