### ISSUE TITLE
After upload plugins, GUI should do screen refresh automatically to see result

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#439]
### Description
Hope it's easy to add many web pages automatic refresh (browser F5). GUI manage tool should be easy to use, user friendly, reflect the result sooner.
OSC->Manage->Plugins any Upload (too SLOW 2 mins to upload Sdn-nsc)
### Expected Behavior
Result should add F5/refresh when the function is done (user friendly)
### Actual Behavior
It did not refresh the browser page to see it's loaded or deleted, user has to manually do F5
### Additional Information
DE3559
### Environment
- OSC Version/Build: master B116
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
dup of #412
