### ISSUE TITLE
Server-Network-Settings-IP Details after Edit, IP addr does not shown full size

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#440]
### Description
Server-Network-Settings-IP Details page has lots space to make it better size to read in the Browser page (now cut to 2/3 numbers)
User has to max Browser to read (resize font does not help) OR go to other page and come back (refresh?)
### Expected Behavior
During graphic design, put "easier to use" in mind, it's a tool to manage.
### Additional Information
DE3687
### Environment
- OSC Version/Build: master Build163
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

### Attached:
https://rally1.rallydev.com/slm/attachment/106421440104/netSetIpDetailImproveS.PNG

**Comment by arvindn05** [comment]
@alin2k remove rally links

You have zoomed in the browser..OSC is expected to maintain usability at a 100% zoom level. Beyond the 100% its on a best effort basis.

- Please reset the zoom to 100% and let us know if this is still problem. 
- Please add browser version. With chrome 60.0.3112.101 and firefox 54.0 (64-bit) we dont see this issue.

**Comment by alin2k** [comment]
Agree it's the zooming issue user can work around, not a bug.

**Comment by alin2k** [comment]
Issue closed, should take out Triage/more-info.
