### ISSUE TITLE
OSC Add VC thru UI works but using API got failed decrypt cipher AES-CTR

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#445]
### Description
Automation used API to Add VC and Job failed, got failed to decrypt cipher AES-CTR
### Expected Behavior
Add VC as UI the same connection with Job passed
### Actual Behavior
Using API to Add VC Job failed
### Steps to Reproduce
Using Python Automation DA.robot Curl sample:
curl -X POST --header 'Content-Type: application/xml' --header 'Accept: application/xml' -d '{
  "id": 0,
  "parentId": 0,
  "name": "vc2",
  "type": "OPENSTACK",
  "controllerIP": "",
  "controllerUser": "",
  "controllerPassword": null,
  "providerIP": "10.3.241.154",
  "providerUser": "admin",
  "providerPassword": "admin123",
  "softwareVersion": "Icehouse",
  "controllerType": "NSC",
  "providerAttributes": {},
  "adminProjectName": "admin",
  "adminDomainId": "default",
  "lastJobState": "COMPLETED",
  "lastJobStatus": "PASSED",
  "lastJobId": 0,
  "skipRemoteValidation": true,
  "forceAddSSLCertificates": false
}' 'https://10.3.240.156:8090/api/server/v1/virtualizationConnectors'
### Environment
- OSC Version/Build: v1b49
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

[APiAddVc-aesctrFailLog.txt](https://github.com/opensecuritycontroller/osc-core/files/1235662/APiAddVc-aesctrFailLog.txt)

**Comment by arvindn05** [comment]
@alin2k Please provide the correct curl request. The request says content type xml but you are providing json.

Also looks like the provider attributes are being sent as empty which should result in an error...please provide more info

**Comment by alin2k** [comment]
Looks like api-doc with Curl works as following input, it's automation code error we need to fix:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "id": 0,
  "parentId": 0,
  "name": "vc",
  "type": "OPENSTACK",
  "controllerIP": "",
  "controllerUser": "",
  "controllerPassword": "",
  "providerIP": "10.3.241.154",
  "providerUser": "admin",
  "providerPassword": "admin123",
  "softwareVersion": "Icehouse",
  "controllerType": "NSC",
  "providerAttributes": {      "ishttps": "false",
      "rabbitUser": "guest",
      "rabbitMQPort": "5672",
      "rabbitMQPassword": "382B744A2E242E0A06AFDB8C5DF18781:7E1E015CFD"},
  "adminProjectName": "admin",
  "adminDomainId": "default",
  "lastJobState": "COMPLETED",
  "lastJobStatus": "PASSED",
  "lastJobId": 0,
  "skipRemoteValidation": true,
  "forceAddSSLCertificates": false
}' 'https://10.3.240.156:8090/api/server/v1/virtualizationConnectors'
===got:===
Response Body
{
  "id": 94,
  "jobId": 472
}
Response Code
200
Response Headers
{
  "date": "Wed, 30 Aug 2017 01:36:09 GMT",
  "content-length": "21",
  "content-type": "application/json"
}

**Comment by ychoma** [comment]
It also fails with   "forceAddSSLCertificates": true

{
  "name": "aaa",
  "type": "OPENSTACK",
  "providerIP": "10.3.205.92",
  "providerUser": "admin",
  "providerPassword": "admin123",
  "softwareVersion": "Icehouse",
  "controllerType": "NSC",
  "providerAttributes": {
    "ishttps": "false",
    "rabbitUser": "guest",
    "rabbitMQPort": "5672",
    "rabbitMQPassword": "guest"
  },
  "adminProjectName": "admin",
  "adminDomainId": "default",
  "skipRemoteValidation": true,
  "forceAddSSLCertificates": true
}

**Comment by ychoma** [comment]
@opensecuritycontroller/osc_triage please triage again

**Comment by emanoelxavier** [comment]
@opensecuritycontroller/osc_triage ack.

**Comment by arvindn05** [comment]
@ychoma can you add the logs, and osc response to the request you have

**Comment by ychoma** [comment]
@arvindn05 @emanoelxavier 

Found the core problem:

It passes with
"rabbitMQPassword": "9665D0E2E45B403DD5D76BED7213C503:FD999F894D"

But failing with 
"rabbitMQPassword": "guest"

**Comment by arvindn05** [comment]
@alin2k please verify

**Comment by alin2k** [comment]
- [x ] Validated     =>    Verified fixed in Version/Build: v08 Build#122
