### ISSUE TITLE
Floating IP pool does not show up for deployments on non-admin tenants

### ISSUE THREAD

**Issue by arvindn05** [opensecuritycontroller/osc-core#457]
### Description
Floating IP pool does not show up for deployments on non-admin tenants on the UI.

### Expected Behavior
Allow user to assign a floating IP for deployments even for non-admin tenants.

### Actual Behavior
 Does not show floating IP pools
### Steps to Reproduce
Create VC/MC/DA
1. Create a deployment spec under the DA and select any non-admin tenant
2. Floating IP pool combo box is not populated

### Additional Information

![image](https://user-images.githubusercontent.com/7297623/30085571-ec5ee12a-924b-11e7-842d-476751211ce7.png)

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT-56-g3debe76
- Cloud Provider Info: Ocata openstack
- Plugin Info: n/a
- Other: n/a

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by mrajora-1** [comment]
Verified with Build Version: 1.0.0-SNAPSHOT (Build:76-g424f129, 2017-09-25T15:49:58Z). 
Created a non-admin tenant and able to see the Floating IP pools while creating a DS. Ds also created successfully. 

![flaoting-ip-displayed-for-non-admin-tenant](https://user-images.githubusercontent.com/28600997/30832552-4a77360e-a200-11e7-9563-96f24bd7f2a0.JPG)

![ds-successfully-created-for-non-admin-tenant](https://user-images.githubusercontent.com/28600997/30832559-52090f8c-a200-11e7-8284-06419d326276.JPG)
