### ISSUE TITLE
Deleting and re-uploading a plugin does not work.

### ISSUE THREAD

**Issue by dmitryintel** [opensecuritycontroller/osc-core#467]
### Description

User should be able to delete and re-install the same plugin multiple times. Currently a correctly built plugin (observed with ISM and NSC plugins) installs fine, but if you delete it and try to re-upload it results in an ERROR status for the plugin. The error message is obscure.

Restarting the OSC makes the error go away.

### Expected Behavior

Deleting and re-installing the same .bar plugin multiple times should work.

### Actual Behavior

Described above. The status in the table of installed plugins is shown as ERROR. The error message non-informative.

### Steps to Reproduce

- Log into OSC.
- Go to Setup > Plugins.
- Add either SampleMgrPlugin or NscSdnControllerPlugin. 
- Wait for it to appear in the list of installed plugins with the status ready. 
- Press DELETE.
- Add the same plugin again.

### Additional Information
The current workaround is restarting the OSC server.
### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT-62-g90f7f93
- Cloud Provider Info: openstack
- Plugin Info: 1.0.0-SNAPSHOT-62-g90f7f93
- Other: n/a

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@dmitryintel please add log information

**Comment by alin2k** [comment]
Verified working in v0.8 Build#122
