### ISSUE TITLE
API Doc for PUT security members needs to be updated

### ISSUE THREAD

**Issue by pravinrajr9** [opensecuritycontroller/osc-core#477]
### Description
PUT /api/server/v1/virtualizationConnectors/{vcId}/securityGroups/{sgId}/members
Body
 ```
{
          "name": string,
          "members": "",
          "id": 105,
          "parentId": 263,
          "api": false
        }
```

https://localhost:8090/api/server/v1/virtualizationConnectors/275/securityGroups/218/members

Body
 ```
 {
          "name":"default-SG",
          "members": null,
          "id": 218,
          "parentId": 275,
          "api": false
        }
```

And the response is:
```
{
  "errorCode": 4000,
  "errorMessages": [
    "Parse exception. Invalid request: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"name\" (class org.osc.core.broker.service.request.UpdateSecurityGroupMemberRequest), not marked as ignorable (5 known properties: \"isApi\", \"members\", \"id\", \"parentId\", \"dto\"])\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2bf1246; line: 2, column: 19] (through reference chain: org.osc.core.broker.service.request.UpdateSecurityGroupMemberRequest[\"name\"])"
  ]
}
```

[ServerSupportBundle.zip](https://github.com/opensecuritycontroller/osc-core/files/1315204/ServerSupportBundle.zip)

When the name parameter is not given, it works fine.

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT (Build:49-ged86223, 2017-09-01T05:37:30Z) 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
This is the expected payload as per the api doc. Name is not one of the fields in the update security group members call. It is part of the member object which you are passing in as null.

The api doc needs to be updated to not have the "dto" with id and parent id fields, but this should not be a blocked. Repurposing the bug to track the api doc issue

@pravinrajr9 please let us know if you agree with the assesment.
```

put /api/server/v1/virtualizationConnectors/{vcId}/securityGroups/{sgId}/members

    Updates the Security Group Members (Openstack Only)
```

```
{
  "dto": {
    "id": 0,
    "parentId": 0
  },
  "id": 0,
  "parentId": 0,
  "members": [
    {
      "id": 0,
      "parentId": 0,
      "name": "string",
      "region": "string",
      "openstackId": "string",
      "type": "string",
      "protectExternal": false,
      "parentOpenStackId": "string",
      "ports": [
        {
          "id": 0,
          "parentId": 0,
          "macAddress": "string",
          "openstackId": "string",
          "ipAddresses": [
            "string"
          ]
        }
      ],
      "label": "string"
    }
  ],
  "api": false
}
```

**Comment by pravinrajr9** [comment]
I agree @arvindn05 and "api" parameter also need to be updated as "isApi" in the API doc.

**Comment by arvindn05** [comment]
@pravinrajr9 please verify and mark the bug as validated with the build number

**Comment by pravinrajr9** [comment]
@arvindn05 "api" parameter is missing in api-doc model schema

**Comment by arvindn05** [comment]
@pravinrajr9 that is expected. we do not want to expose that flag via api.

Please follow the steps below to mark the issue as validated.

https://github.com/opensecuritycontroller/community/blob/master/development/issue_tracking.md#assignee-flow
