### ISSUE TITLE
Notifications - Automatic Sync of SG not happening, when a new VM is added to an SG which was created with Selection 'All Servers belonging to a Project' 

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#479]
### Description
Notifications - Automatic Sync of SG not happening, when a new VM is added to an SG which was created with Selection 'All Servers belonging to a Project' 

### Expected Behavior
Ths SG sync should be automatically triggered when SG is created with Selection 'All Servers' belonging to a Project' and a new VM is added to the Project. 

### Actual Behavior
Automatic Sync of SG not happening, when a new VM is added to an SG which was created with Selection 'All Servers belonging to a Project'. Only a manual Sync triggers the Sync and  then the number of VMs are getting updated on the Security Group page under Members column. 

### Steps to Reproduce
Create a VC, MC, DA, DS
Then create a SG with Selection - All servers belonging to a Project
From openstack launch another instance on the same project. 
Notifications should be working and an automatic sync should be triggered for SG Job.

### Additional Information
Automatic Sync is not happening. A manual sync triggers the SG job and updates the number of VMs. 
The deletion of new VM is working fine  but Add is not. 
Have 2 VMs - cirros-victim and cirros-attacker to start with and added VM cirros-test later for testing. 

### Environment
- OSC Version/Build: Version 1.0.0-SNAPSHOT (Build:66-g88ebb92, 2017-09-16T16:23:23Z
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

[securityBroker (3).txt](https://github.com/opensecuritycontroller/osc-core/files/1316030/securityBroker.3.txt)

**Comment by arvindn05** [comment]
@mrajora-1 https://github.com/opensecuritycontroller/osc-core/issues/479 Please update that bug. closing this one.
