### ISSUE TITLE
After deleting all plugins OSC UI looks strange

### ISSUE THREAD

**Issue by ychoma** [opensecuritycontroller/osc-core#480]
### Description
Add plugin delete plugin and refresh - the UI now won't look like it was before adding the plugin - see attached file

### Expected Behavior
The UI should look like just before adding the plugins

### Actual Behavior
UI will look strange see attached file

### Steps to Reproduce
Add plugin delete plugin and refresh 

### Environment
- OSC Version/Build: **Version: 1.0.0-SNAPSHOT (Build:68-gdbdf499, 2017-09-19T21:58:35Z)**
![strangeui](https://user-images.githubusercontent.com/26880884/30619030-077b9b68-9d52-11e7-829f-1d2b91dadaea.png)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@ychoma please add more information. The screenshot is too low resolution to make out anything.

Please highlight the ui issue when you upload the new image

**Comment by ychoma** [comment]
Minor and look reasonable actually just different than in another time.
