### ISSUE TITLE
API Call for POST DA fails

### ISSUE THREAD

**Issue by pravinrajr9** [opensecuritycontroller/osc-core#496]
POST /api/server/v1/distributedAppliances

Body
`{
  "id": 0,
  "parentId": 0,
  "name": "string",
  "applianceSoftwareVersionName": "string",
  "applianceModel": "string",
  "virtualizationSystems": [
    {
      "id": 0,
      "parentId": 0,
      "name": "string",
      "distributedAppliance": "string",
      "virtualizationConnectorName": "string",
      "virtualizationType": "OPENSTACK",
      "domainName": "string",
      "vcId": 0,
      "domainId": 0,
      "encapsulationType": "VLAN",
      "markForDeletion": false
    }
  ],
  "lastJobState": "string",
  "lastJobStatus": "string",
  "lastJobId": 0,
  "markForDeletion": false,
  "jobId": 0,
  "applianceManagerConnectorName": "string",
  "mcId": 0,
  "applianceId": 0
}`

When DomainId in virtualSystem is given 0
https://10.3.205.104/POST /api/server/v1/distributedAppliances

`{
                "name": "default-DA",
                "managerConnectorName": "default-MC",
                "managerConnectorId": "15",
                "applianceSoftwareVersionId": "1",
                "applianceModel": "CIRROS-TCPD",
                "applianceSoftwareVersionName": "0.3.0.5000",
                "secretKey": "dummy1234",
                "markForDeletion": false,
                "virtualSystem": [
                    {
                        "domainId": 0,
                        "domainName": "",
                        "markForDeletion": false,
                        "vcId": "13",
                        "virtualizationConnectorName": "default-VC",
                        "virtualizationType": "OPENSTACK",
                        "encapsulationType": "VLAN"
                    }
                ]
            }`

Response:
`{
  "errorCode": 4000,
  "errorMessages": [
    "Open Security Controller: Domain used in Virtual System default-VC cannot be found."
  ]
}`

When domain id inside virtualSystem is given as null
https://10.3.205.104/POST /api/server/v1/distributedAppliances

`{
                "name": "default-DA",
                "managerConnectorName": "default-MC",
                "managerConnectorId": "15",
                "applianceSoftwareVersionId": "1",
                "applianceModel": "CIRROS-TCPD",
                "applianceSoftwareVersionName": "0.3.0.5000",
                "secretKey": "dummy1234",
                "markForDeletion": false,
                "virtualSystem": [
                    {
                        "domainId": null,
                        "domainName": "",
                        "markForDeletion": false,
                        "vcId": "13",
                        "virtualizationConnectorName": "default-VC",
                        "virtualizationType": "OPENSTACK",
                        "encapsulationType": "VLAN"
                    }
                ]
            }`

Response:
`{
  "errorCode": 4000,
  "errorMessages": [
    "Open Security Controller: Domain Id should not have an empty value."
  ]
}`

The above call with parameter works in build version: 1.0.0-SNAPSHOT (Build:49-ged86223, 2017-09-01T05:37:30Z)

- OSC Version/Build: 1.0.0-SNAPSHOT (Build:80-gcf47d8d, 2017-09-26T07:19:49Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by larkinscarvalho** [comment]
We have added support for multiple policies.
Please create the domain and policies before creating DA.


POST API to create Domain: https://OSC_IP:8090/testplugin/sm/domains
Body: 
{
               "name":"Default"
}
Response:
**Domain ID**

POST API to create Policies: https://OSC_IP:8090/testplugin/sm/domains/**domain_id**/policies
Body:
{
               "name":"ODD"
}
Response:
**Policy ID**

**Comment by larkinscarvalho** [comment]
@pravinrajr9 I have created domain and policies for OSC 10.3.205.104. Please let me know if you see any issues.

**Comment by pravinrajr9** [comment]
@larkinscarvalho May I know the updated version of API and parameters for creating Domain, Policies and DA
