### ISSUE TITLE
Multiple Inspection Policy values to be separated by a space when displayed on Policy Mappings Page on OSC UI

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#504]
### Description
Multiple Inspection Policy values to be separated by a space when displayed on Policy Mappings Page on OSC UI
### Expected Behavior
Multiple Inspection Policy values should be separated by a space when displayed on Policy Mappings Page on OSC UI
### Actual Behavior
Multiple Inspection Policy values to be separated by a space when displayed on Policy Mappings Page on OSC UI
### Steps to Reproduce
1. Create VC, MC, DA, DS, SG
2. Create a domain and multiple policies on ISM  
3. Bind multiple policies using the API - PUT /api/server/v1/virtualizationConnectors/{vcId}/securityGroups/{sgId}/bindings
4. SG will be binded. 
5. From Distributed Appliances, check Traffic Policy Mappings page. 
6. Under Inspection Policy column, the policies are displayed accurately. However it will be nice to have them separated by a space, so UI looks cleaner. 

### Additional Information
Screen shot attached - should suffice. No logs needed for this defect. 

### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:78-gc0de361, 2017-09-25T22:59:09Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![3-space-separate-multiple-policies](https://user-images.githubusercontent.com/28600997/31030621-df453ddc-a50a-11e7-9883-92e7f5e4b3a2.JPG)

**Comment by arvindn05** [comment]
will be handled by @larkinscarvalho as part of his next checkin in this area.

**Comment by arvindn05** [comment]
@mrajora-1 please veirfy

**Comment by mrajora-1** [comment]
Verified with Version: 1.0.0-SNAPSHOT (Build:105-g85eff16, 2017-10-10T03:12:47Z)
See multiple policies separated with commas. 
Hence closing the issue.

![bug-504-fixed](https://user-images.githubusercontent.com/28600997/31400933-1a4ece72-ada6-11e7-8bb8-b1cde9d52c7e.JPG)
