### ISSUE TITLE
When there is SFC associated DA which cannot be force deleted, error msg needs to be detailed

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#505]
### Description
API now can POST, PUT, GET, DELETE SFC with VS in DA. When user tries to delete a DA from UI or API, not knowing why it has Job Failed with reason: "The transaction rolled back due to a failure"
### Expected Behavior
Job Failed error message could be "DA has SFC associated, cannot delete or force-delete this DA"
(May be in the near future, it allows to force-delete which can delete SFC 1st then DA?)
### Actual Behavior
Job Failed and user may not know why or when there is a SFC associated DA (UI not support SFC yet)
### Steps to Reproduce
1)OSC has VC, MC, SF, DA added.
2)Use API thru oscIpaddr:8090/api-doc to POST a SFC with DA/VS associated (GET to check this SFC)
3)From UI, delete or force-delete this DA and saw Job Failed: "The transaction rolled back due to a failure"
### Environment
- OSC Version/Build: 0.8 Build#85
- Cloud Provider Info: NA
- Plugin Info: NA
- Other:

### Status
- [x] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

### Logs attached
[sfcExistedCannotDelDAErrMsgImproveLog500.txt](https://github.com/opensecuritycontroller/osc-core/files/1345842/sfcExistedCannotDelDAErrMsgImproveLog500.txt)

**Comment by karimull** [comment]
This is issue is fixed in current Builds. Please verify

**Comment by alin2k** [comment]
- [ x] Validated     =>    Verified fix in Version/Build: v0.8 Build#123:
![sfcdadeleteerrmsgs](https://user-images.githubusercontent.com/11319375/31693032-571f87fa-b351-11e7-9243-fe8afd07e977.PNG)
