### ISSUE TITLE
Creation of Deployment Specification fails on a fresly installed sdnnsc plugin

### ISSUE THREAD

**Issue by sudhirappaji** [opensecuritycontroller/osc-core#523]
### Description
Failure while creating the DS, with the following error message for the JOB task  “Deploying SVA for Distributed Appliance Instance …”  with the error message “ The Resource Provided has been reclaimed because the factory service that provides it was released”.
### Expected Behavior
DS creation should be permitted and mandatory in the above scenario.
### Steps to Reproduce
DS failure with the message "The Resource Provided has been reclaimed because the factory service that provides it was released".
### Additional Information
With the following workaround scenario, the problem is not reproduced:
1.	Reload the sdnnsc plugin after deleting the existing DA/DS.
2.	Reset/reboot OSC
3.	Run OSC and create VC, MC,DA,DS, SG, SGBind, SGunBind, and delete SG, DS,DA,MC and VC.
4.	All of the above tests are passing with this work around.

### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:97-g601eb9e, 2017-10-07T19:30:12Z
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
from the email:

> First time when we create OSC via fresh OVL deployment, everything works perfectly. We can create VC,MC, DA and DS.
> 
> Then delete DS,DA,MC and VC and delete the sdnnsc plugin and reinstall/load the same plugin (from standard build#97), and then go ahead and create VC,MC, DA and DS. Now DS fails with the above message. I tried by deleting the NSC DB file this does not help and since DS creation fails, NSC DB does not get re-created.

Please follow the above steps to reproduce.

**Comment by arvindn05** [comment]
@mrajora-1 please validate.

**Comment by mrajora-1** [comment]
Tested and verified with Build Version: 1.0.0-SNAPSHOT (Build:128-gabfa924, 2017-10-20T07:21:49Z)
Started with Build 123 and was able to reproduce the issue. 
Upgraded the OSC to Build 128. Then did a Sync of the failed DS, Job Passed
The went back and repeated the same steps with which had seen the issue earlier and do not see it any more. 
Hence closing the bug. 

[securityBroker-DS-failure-fixed.log](https://github.com/opensecuritycontroller/osc-core/files/1402982/securityBroker-DS-failure-fixed.log)
