### ISSUE TITLE
Unable to delete the plugin from plugin menu option

### ISSUE THREAD

**Issue by sudhirappaji** [opensecuritycontroller/osc-core#524]
### Description
After installing the OSC from Build#96, delete option does not appear due to nauge plugin OSGI error. 
### Actual Behavior
deletion button on the plugin should appear.
### Steps to Reproduce
- Deploy the OSC Build#96.
- Go to Plugin Menu
- Delete option for the plugin does not appear due to nauge plugin error message is too long.
### Environment
- OSC Version/Build: OSC Build#95.
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [x] Reproduced
- [x] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by alin2k** [comment]
- [x ] Validated     =>    Verified fix in Version/Build: v0.8 Build#123

**Comment by emanoelxavier** [comment]
This issue is still happening on later versions of OSC. For this to repro though one needs a defective plugin.

**Comment by alin2k** [comment]
- [x] Validated     =>    Verified fix in Version/Build: v0.8 Build#125
