### ISSUE TITLE
Do not allow binding in neutron-sfc plugin from UI

### ISSUE THREAD

**Issue by karimull** [opensecuritycontroller/osc-core#540]
### Description
SFC binding is only allowed through APIs as UI Is not supported yet.

### Expected Behavior
User should shown an error when trying to bind services to SG supporting neutron-sfc .
### Actual Behavior
SFC binding is allowed through UI.
### Steps to Reproduce
create VirtualizationConnector- with neutron sfc
create Security group
Bind a Security Group  with services.
### Additional Information
Arvind found this issue during story acceptance . Tracing as an issue
### Environment
- OSC Version/Build:  108
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [x ] Reproduced
- [x ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@karimull just to clarify, the issue is not the below that SFC binding is allowed via UI

In neutron SFC case, creating individual Security Group interfaces via the bind dialog/service should not be allowed. Currently this is allowed.

**Comment by arvindn05** [comment]
DE5294

**Comment by mrajora-1** [comment]
Verified with Version: 1.0.0-SNAPSHOT (Build:123-gbf90939, 2017-10-18T07:20:37Z)
Now I am getting an error when binding or unbinding SFC-SG from UI

![bug-540-no-binding-from-ui](https://user-images.githubusercontent.com/28600997/31739449-c302d556-b402-11e7-8806-cc5d2472fb79.JPG)

![bug-540-no-unbinding-from-ui](https://user-images.githubusercontent.com/28600997/31739493-eb06b1d0-b402-11e7-8dbb-6038ec5feea2.JPG)

**Comment by mrajora-1** [comment]
Note that the error is same whether we bind or unbind. Was thinking that unbind error should have been different. Discussed with Karim and he suggested that the same error was kept as the operation is still bind.
