### ISSUE TITLE
Creation of DA fails with error - Failure occurred obtaining the resource provider (using Neutron-sfc plugin)

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#542]
### Description
Creating a DS fails with error – Failure occurred obtaining the resource provider (using Neutron-sfc plugin)
### Expected Behavior
DS Creation should have been successful 
### Actual Behavior
Creating a DS fails with error – Failure occurred obtaining the resource provider
### Steps to Reproduce
Create VC (SDN Controller - Neutron-sfc), MC, DA and then DS
Creating a DS fails with error – Failure occurred obtaining the resource provider
### Additional Information
Restart openstack. Sync of failed DS will not make it pass but deleting the DA and recreating the DA, DS will result in successful creation of DS
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

[securityBroker-DS.log](https://github.com/opensecuritycontroller/osc-core/files/1377668/securityBroker-DS.log)

**Comment by arvindn05** [comment]
@mrajora-1  is this a dup? #523

**Comment by arvindn05** [comment]
tried this

**Comment by arvindn05** [comment]
tried to reproduce this issue in my OSC with version 1.0.0-SNAPSHOT (Build:114-gd819a4f)

Did not encounter it with the steps specified. Closing the issue, reopen if you still see it.

I will follow the steps in #523 to see if that is a valid scenario

**Comment by mrajora-1** [comment]
Created a DS with Builds 114 and 118 - was successful. Not seeing the issue in 114 and 118 builds.

**Comment by mrajora-1** [comment]
Build1.0.0-SNAPSHOT-114-gd819a4f
Build1.0.0-SNAPSHOT-118-g0a08063
