### ISSUE TITLE
Error message to be more appropriate when deleting a DS without deleting the SFC

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#544]
### Description
Error message to be more appropriate when deleting a DS without deleting the SFC
### Expected Behavior
Error message should be more suggestive - e.g. DS cannot be deleted unless the SFC is deleted 
### Actual Behavior
Error message when deleting DS when SFC is not deleted -  Deployment Spec is currently protecting a workload
### Steps to Reproduce
- Create a VC (using SDN - Neutron-sfc), MC, DA, DS, SG. 
- Create SFC. 
- Bind the SG to SFC. 
- Now delete the SG. 
- Delete DS
- Get an error message - Deployment Spec is currently protecting a workload
This suggests that probably there is a SG being protected, whereas, in reality we need to delete the SFC to delete the DS. 
### Additional Information
WORKAROUND - delete the SFC and then DS delete will be successful 
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![deleting-ds-protecting-workload-error](https://user-images.githubusercontent.com/28600997/31480557-4e3696a6-aed3-11e7-8418-48e9fcfafeaa.JPG)

**Comment by arvindn05** [comment]
dup of #543
