### ISSUE TITLE
User should not be allowed to bind an SG from OSC UI when there is an SFC configured from the API

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#546]
### Description
User should not be allowed to bind an SG from OSC UI when there is an SFC configured from the API
### Expected Behavior
User should not be allowed to bind an SG from OSC UI when there is an SFC configured from the API
### Actual Behavior
Currently I am able to bind the SG from the OSC UI
### Steps to Reproduce
- Create a VC (using SDN - Neutron-SFC_ , MC, DA, DS
- Configure SFC through the API
- Create an SG and bind from the UI
- The Job passes 
The bind operation from UI should be blocked/prevented. 
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![bind-succeeds-from-ui-when-only-bind-from-api-should-be-allowed](https://user-images.githubusercontent.com/28600997/31549785-122c55e4-afe4-11e7-939a-3a6875f97e43.JPG)

[ServerSupportBundle (33).zip](https://github.com/opensecuritycontroller/osc-core/files/1382828/ServerSupportBundle.33.zip)

**Comment by arvindn05** [comment]
dup of #540
