### ISSUE TITLE
Network Element id missing from API - GET SG response

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#548]
### Description
Network Element id missing from API - GET SG 
### Expected Behavior
Will be good to include -Network Element id, in the response of GET /api/server/v1/virtualizationConnectors/{vcId}/securityGroups
### Actual Behavior
Network Element id missing from API - GET SG members
### Steps to Reproduce
- Create VC, MC, DA, DS, SG with at least one member. 
- Create an SFC through the API 
- Bind the SG
- Use the Get API to retrieve SGs. 
- Will be good to include Network element Id in the response. 
### Additional Information
Logs not needed. 
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [x] Reproduced
- [x] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by larkinscarvalho** [comment]
Network element Id is associated with Security Group.
We need to add network element id to the SG get API.

**Comment by mrajora-1** [comment]
Updated the bug with API get SG (instead of get SG members)

**Comment by arvindn05** [comment]
@mrajora-1 please validate

**Comment by mrajora-1** [comment]
Verified with Build Version: 1.0.0-SNAPSHOT (Build:118-g0a08063, 2017-10-17T07:21:29Z)
I do see Network Element ID in the Get SG API. 

![network-element-id-shown-on-get-sg-api](https://user-images.githubusercontent.com/28600997/31678840-371ad482-b324-11e7-969c-82eaebf04f3e.JPG)
