### ISSUE TITLE
Disable SGI binding update for multi-policy mapping supported bindings

### ISSUE THREAD

**Issue by larkinscarvalho** [opensecuritycontroller/osc-core#551]
### Description
Multi-policy mapping is not supported through UI. Once, we create multi-policy mapping, we should not be able to update binding through UI.

### Expected Behavior
Disable SGI binding for existing multi-policy mapping

### Actual Behavior
Policy drop down menu is editable

### Steps to Reproduce

- Create VC (using NSC), MC, 1DA, 1DS, 1SG
- Bind SG with multiple policies through rest API
- Click on the SG Bind button to view the SGI binding
- Uncheck the service enabled checkbox
- Then, again check service enabled checkbox, Policy menu is editable

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT (Build:113)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [x] Reproduced
- [x] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![sgi_policy_ui](https://user-images.githubusercontent.com/9063674/31565068-45900d00-b01a-11e7-83fb-a4c85cc16b20.JPG)

**Comment by arvindn05** [comment]
@larkinscarvalho lets drop if its high effort or has high chance for regression. Please let us know your evaluation

**Comment by arvindn05** [comment]
addressed by https://github.com/opensecuritycontroller/osc-core/pull/585

**Comment by ychoma** [comment]
It works fine now:
Verfied with Version: 1.0.0-SNAPSHOT (Build:144-g9c773e4, 2017-10-27T07:21:25Z)

If have already multiple policies - the combo box for policies is disabled and if you uncheck and check and then click OK remembers the multiple policies.

If you uncheck and click OK  - it unbind

When checking it again - the combo box is enabled and you can choose a single policy that you want from the UI it works

When used SFC - the unbind is not allowed through UI as expected
