### ISSUE TITLE
OSC 0.8 Build110, restore DB popup text should ask for password entry, not create/set passwd

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#553]
### Description
Popup text message is misleading (should not use same as Backup DB function which Create password)
Screenshot attached.
### Expected Behavior
Popup text could be Please enter database backup password, Password
### Actual Behavior
(misleading when click "Restore" DB) Create database backup password, Set password..
### Steps to Reproduce
1)OSC->Manage->Server->Maintenance->Backup Database (may need backup 1st with a password set)
2)OSC->Manage->Server->Maintenance->Restore Database, Choose step1)saved .dbb file, click Restore
3)Saw "Create database.." popup message which is misleading
### Additional Information
Screenshot:
![restoredbpasswdentrytextwrongs](https://user-images.githubusercontent.com/11319375/31568843-82038e72-b02b-11e7-9565-082746f1e666.PNG)
Log:
[restore08dbPasswdTextWrongLog500.txt](https://github.com/opensecuritycontroller/osc-core/files/1384169/restore08dbPasswdTextWrongLog500.txt)

### Environment
- OSC Version/Build: v0.8B110
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
duping to #558
