### ISSUE TITLE
Receiving Error - Cannot find port group id, when editing DS and enabling/disabling hosts

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#566]
### Description
Receiving Error - Cannot find port group id, when editing DS and enabling/disabling hosts
### Expected Behavior
- DS Sync should pass without errors while editing DS and enabling/disabling hosts
- Remove the exclamation after the port group ID in the error. 
### Actual Behavior
- Receiving Error - Cannot find port group id, when editing DS and enabling/disabling hosts
- There is also an exclamation at the end of the port ID
### Steps to Reproduce
- Create VC (SFC), MC, DA
- Create DS with 2 hosts selected - job is passed
- Edit the DS and disable host 2 - Job passed
- Edit the DS and enable host 1 and disable host 2 - Job fails with error - Cannot find port group by id: a3dfbf82-701d-424b-a51c-55b94a3de420!
- Edit the DA and add host 2 again - Still the DS Sync fails with the same error as above
### Additional Information
- DS is active on Openstack
- Port Group ID is seen on Get DS API
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:118-g0a08063, 2017-10-17T07:21:29Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![cannot-find-port-grp-by-id-error-editing-ds-w-2-hosts](https://user-images.githubusercontent.com/28600997/31701392-ea5b497c-b384-11e7-886a-0f260230e1cc.JPG)

![appliance-instance-active-on-openstack](https://user-images.githubusercontent.com/28600997/31701401-fd297bc8-b384-11e7-9399-a74084413097.JPG)

![port-group-id-seen-on-get-ds](https://user-images.githubusercontent.com/28600997/31701404-058a7010-b385-11e7-9539-40e9b82b3ba3.JPG)

[securityBroker.log](https://github.com/opensecuritycontroller/osc-core/files/1393465/securityBroker.log)

**Comment by arvindn05** [comment]
DE5334

**Comment by mrajora-1** [comment]
Verified with Version: 1.0.0-SNAPSHOT (Build:140-gb301029, 2017-10-24T07:22:46Z)
I edited the DS enabling/disabling host1 and host2. Each time the DS creation passed with no errors. 

[securityBroker-Port-Grp-issue-fixed.log](https://github.com/opensecuritycontroller/osc-core/files/1412739/securityBroker-Port-Grp-issue-fixed.log)
