### ISSUE TITLE
Release Build#148 Alerts ShowPending does not work but same as ShowAll

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#595]
### Description
OSC Alerts has two buttons at top right, "Show Pending" should not show Acknowledged alerts
### Expected Behavior
"Show Pending" should not show Acknowledged alerts, only show unAck alerts
### Actual Behavior
"Show Pending" has same as "Show All"
### Steps to Reproduce
1)Create alerts
2)Click Acknowledge on some/obe alert
3)Click "Show Pending" and same as "Show All", list also Acked alerts
### Additional Information: screenshot and log:
![showpendinghasackalertss](https://user-images.githubusercontent.com/11319375/32388665-a5723966-c085-11e7-9b70-f09bc081cd2c.PNG)
[alertAllPendingLog700.txt](https://github.com/opensecuritycontroller/osc-core/files/1442119/alertAllPendingLog700.txt)

### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@alin2k please add screenshots and logs and more information

**Comment by sudhirappaji** [comment]
@alin2k , please provide the information, otherwise we will close this issue in two weeks.

**Comment by alin2k** [comment]
Interesting, I was added screenshot and log, not seeing it?:
In "Additional Information: screenshot and log:"

**Comment by sudhirappaji** [comment]
Ensure that API behavior is not impacted on fixing this bug.
