### ISSUE TITLE
According to the file "Building OSC Images" ,when I Create CentOS Schroot Environment,I met a problem,so I cannot get the OSC image

### ISSUE THREAD

**Issue by liuxuejiao123** [opensecuritycontroller/osc-core#597]
### Description

According to the file "Building OSC Images" ,when I Create CentOS Schroot Environment,I met a problem,so I cannot get the OSC image , 
the error infomation is:
root@HGH1000054403:~/OpenSecurityController/osc-core/osc-server-bom/bin# ./create-centos 
./create-centos: line 1: $'\r': command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rpm
./create-centos: line 3: $'\r': command not found
mkdir: invalid option -- 'b'
Try 'mkdir --help' for more information.
mkdir: invalid option -- 'b'
Try 'mkdir --help' for more information.
mkdir: invalid option -- 'b'
Try 'mkdir --help' for more information.
mount: invalid option -- 'b'
Usage: mount -V                 : print version
       mount -h                 : print this help
       mount                    : list mounted filesystems
       mount -l                 : idem, including volume labels
So far the informational part. Next the mounting.
The command is `mount [-t fstype] something somewhere'.
Details found in /etc/fstab may be omitted.
       mount -a [-t|-O] ...     : mount all stuff from /etc/fstab
       mount device             : mount device at the known place
       mount directory          : mount known device here
       mount -t type dev dir    : ordinary mount command
Note that one does not really mount a device, one mounts
a filesystem (of the given type) found on the device.
One can also mount an already visible directory tree elsewhere:
       mount --bind olddir newdir
or move a subtree:
       mount --move olddir newdir
One can change the type of mount containing the directory dir:
       mount --make-shared dir
       mount --make-slave dir
       mount --make-private dir
       mount --make-unbindable dir
One can change the type of all the mounts in a mount subtree
containing the directory dir:
       mount --make-rshared dir
       mount --make-rslave dir
       mount --make-rprivate dir
       mount --make-runbindable dir
A device can be given by name, say /dev/hda1 or /dev/cdrom,
or by label, using  -L label  or by uuid, using  -U uuid .
Other options: [-nfFrsvw] [-o options] [-p passwdfd].
For many more details, say  man 8 mount .
mount: invalid option -- 'b'
Usage: mount -V                 : print version
       mount -h                 : print this help
       mount                    : list mounted filesystems
       mount -l                 : idem, including volume labels
So far the informational part. Next the mounting.
The command is `mount [-t fstype] something somewhere'.
Details found in /etc/fstab may be omitted.
       mount -a [-t|-O] ...     : mount all stuff from /etc/fstab
       mount device             : mount device at the known place
       mount directory          : mount known device here
       mount -t type dev dir    : ordinary mount command
Note that one does not really mount a device, one mounts
a filesystem (of the given type) found on the device.
One can also mount an already visible directory tree elsewhere:
       mount --bind olddir newdir
or move a subtree:
       mount --move olddir newdir
One can change the type of mount containing the directory dir:
       mount --make-shared dir
       mount --make-slave dir
       mount --make-private dir
       mount --make-unbindable dir
One can change the type of all the mounts in a mount subtree
containing the directory dir:
       mount --make-rshared dir
       mount --make-rslave dir
       mount --make-rprivate dir
       mount --make-runbindable dir
A device can be given by name, say /dev/hda1 or /dev/cdrom,
or by label, using  -L label  or by uuid, using  -U uuid .
Other options: [-nfFrsvw] [-o options] [-p passwdfd].
For many more details, say  man 8 mount .
./create-centos: line 13: $'\r': command not found
./create-centos: line 22: $'\r': command not found
: octal number out of rangemask: 000
./create-centos: line 24: $'\r': command not found
./create-centos: line 25: rpmdb: command not found
-bootstrap/RPM-GPG-KEY-CENTOS6.pub: No such file or directory
./create-centos: line 27: rpm: command not found
./create-centos: line 28: yum: command not found
./create-centos: line 29: $'\r': command not found
mkdir: invalid option -- 'b'
Try 'mkdir --help' for more information.
mount: invalid option -- 'b'
Usage: mount -V                 : print version
       mount -h                 : print this help
       mount                    : list mounted filesystems
       mount -l                 : idem, including volume labels
So far the informational part. Next the mounting.
The command is `mount [-t fstype] something somewhere'.
Details found in /etc/fstab may be omitted.
       mount -a [-t|-O] ...     : mount all stuff from /etc/fstab
       mount device             : mount device at the known place
       mount directory          : mount known device here
       mount -t type dev dir    : ordinary mount command
Note that one does not really mount a device, one mounts
a filesystem (of the given type) found on the device.
One can also mount an already visible directory tree elsewhere:
       mount --bind olddir newdir
or move a subtree:
       mount --move olddir newdir
One can change the type of mount containing the directory dir:
       mount --make-shared dir
       mount --make-slave dir
       mount --make-private dir
       mount --make-unbindable dir
One can change the type of all the mounts in a mount subtree
containing the directory dir:
       mount --make-rshared dir
       mount --make-rslave dir
       mount --make-rprivate dir
       mount --make-runbindable dir
A device can be given by name, say /dev/hda1 or /dev/cdrom,
or by label, using  -L label  or by uuid, using  -U uuid .
Other options: [-nfFrsvw] [-o options] [-p passwdfd].
For many more details, say  man 8 mount .
mount: invalid option -- 'b'
Usage: mount -V                 : print version
       mount -h                 : print this help
       mount                    : list mounted filesystems
       mount -l                 : idem, including volume labels
So far the informational part. Next the mounting.
The command is `mount [-t fstype] something somewhere'.
Details found in /etc/fstab may be omitted.
       mount -a [-t|-O] ...     : mount all stuff from /etc/fstab
       mount device             : mount device at the known place
       mount directory          : mount known device here
       mount -t type dev dir    : ordinary mount command
Note that one does not really mount a device, one mounts
a filesystem (of the given type) found on the device.
One can also mount an already visible directory tree elsewhere:
       mount --bind olddir newdir
or move a subtree:
       mount --move olddir newdir
One can change the type of mount containing the directory dir:
       mount --make-shared dir
       mount --make-slave dir
       mount --make-private dir
       mount --make-unbindable dir
One can change the type of all the mounts in a mount subtree
containing the directory dir:
       mount --make-rshared dir
       mount --make-rslave dir
       mount --make-rprivate dir
       mount --make-runbindable dir
A device can be given by name, say /dev/hda1 or /dev/cdrom,
or by label, using  -L label  or by uuid, using  -U uuid .
Other options: [-nfFrsvw] [-o options] [-p passwdfd].
For many more details, say  man 8 mount .
cp: invalid option -- 'o'
Try 'cp --help' for more information.
cp: invalid option -- 'o'
Try 'cp --help' for more information.
./create-centos: line 35: $'\r': command not found
chroot: invalid option -- 'b'
Try 'chroot --help' for more information.
chroot: invalid option -- 'b'
Try 'chroot --help' for more information.
chroot: invalid option -- 'b'
Try 'chroot --help' for more information.
: No such file or directorymnt/sysimage/etc/rpm/macros
./create-centos: line 40: $'\r': command not found
umount: invalid option -- 'b'
Usage: umount -h | -V
       umount -a [-d] [-f] [-r] [-n] [-v] [-t vfstypes] [-O opts]
       umount [-d] [-f] [-r] [-n] [-v] special | node...
umount: invalid option -- 'b'
Usage: umount -h | -V
       umount -a [-d] [-f] [-r] [-n] [-v] [-t vfstypes] [-O opts]
       umount [-d] [-f] [-r] [-n] [-v] special | node...
umount: invalid option -- 'b'
Usage: umount -h | -V
       umount -a [-d] [-f] [-r] [-n] [-v] [-t vfstypes] [-O opts]
       umount [-d] [-f] [-r] [-n] [-v] special | node...
umount: invalid option -- 'b'
Usage: umount -h | -V
       umount -a [-d] [-f] [-r] [-n] [-v] [-t vfstypes] [-O opts]
       umount [-d] [-f] [-r] [-n] [-v] special | node...
./create-centos: line 45: $'\r': command not found
rm: invalid option -- 'b'
Try 'rm --help' for more information.
./create-centos: line 47: $'\r': command not found
./create-centos: line 54: $'\r': command not found
find: missing argument to `-exec'
find: missing argument to `-exec'
find: missing argument to `-exec'
./create-centos: line 58: $'\r': command not found
./create-centos: line 70: $'\r': command not found
./create-centos: line 71: /etc/schroot/chroot.d/centos.conf: No such file or directory
./create-centos: line 80: $'\r': command not found
./create-centos: line 81: /etc/schroot/default/fstab: No such file or directory
./create-centos: line 84: $'\r': command not found
./create-centos: line 88: $'\r': command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package yum
root@HGH1000054403:~/OpenSecurityController/osc-core/osc-server-bom/bin# 

### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@karimull can you help out?

@liuxuejiao123 looks like the line ending on your checked out file are incorrect. There might be some settings you would need to change on git so line endings are checked out correctly. You need unix line endings on the shell files.

**Comment by arvindn05** [comment]
@karimull please evaluate and let us know if this is a valid issue.

**Comment by liuxuejiao123** [comment]
the line ending problem is solved
