### ISSUE TITLE
Add OSC release repository in the pom files to facilitate creation of release branches

### ISSUE THREAD

**Issue by emanoelxavier** [opensecuritycontroller/osc-core#600]
The osc-core pom files for osc-service-api, export and osc-ui only have the snapshot repository. We should include also the release repository url, similar to https://github.com/opensecuritycontroller/security-mgr-sample-plugin/blob/master/pom.xml#L12 . This facilitates the creation of release branches since updating the repositories becomes unecessary.

**Comment by arvindn05** [comment]
i would add the repositories at the https://github.com/opensecuritycontroller/osc-core/blob/master/pom.xml not at the individual pom modules.

we can clean up the repositories at the individual module level.

**Comment by emanoelxavier** [comment]
Fixed by #601
