### ISSUE TITLE
got error message box during security group binding for Panorama

### ISSUE THREAD

**Issue by ruxxon** [opensecuritycontroller/osc-core#622]
### Description
got error message box during security group binding for Panorama
### Expected Behavior
should be successfully binding and show tag in Panorma
### Actual Behavior
got error message box during security group binding for Panorama 
![image](https://user-images.githubusercontent.com/13109175/33951365-0110552a-dfec-11e7-8e20-5c4f92d7561c.png)
[OSC_bind_log.txt](https://github.com/opensecuritycontroller/osc-core/files/1556334/OSC_bind_log.txt)

### Environment
- OSC Version/Build: 0.8.0
- Cloud Provider Info: OSP10
- Plugin Info: Panorama Plugin
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by ruxxon** [comment]
it can be easy reproduced.

**Comment by sudhirappaji** [comment]
@dmitryintel , could you check and provide your findings?

**Comment by dmitryintel** [comment]
I am working on polishing off the implementation for this plugin. Currently binding/unbinding works. Pull request submitted.
